export const caseStudies = {
  meeting: {
    eyebrow: "Local-first voice intelligence",
    title: "Meeting Whisperer",
    subtitle: "A private meeting recorder that captures microphone and system audio, produces speaker-aware transcripts, and keeps every recording searchable.",
    accent: "pink",
    repository: "https://github.com/TJ-Rustamov/Meeting-whisperer",
    stack: ["React", "FastAPI", "WebSockets", "faster-whisper", "Silero VAD", "pyannote", "SQLite", "Docker"],
    metrics: [["Real captures", "Recorder, history, and transcript"], ["Local speech AI", "STT and diarization stay self-hosted"], ["Optional cloud", "LLM only for post-processing"]],
    architecture: [
      ["Capture", "React, MediaRecorder, and AudioWorklet collect microphone and desktop audio.", "Local"],
      ["Stream", "FastAPI and WebSockets move live audio and transcript events through the application.", "Self-hosted"],
      ["Transcribe", "Silero VAD, faster-whisper, and optional pyannote process speech and speakers.", "Local model"],
      ["Store", "SQLite plus local audio and video files preserve meetings and transcript history.", "Local"],
      ["Enrich", "An external LLM can be enabled for summaries or cleanup; core transcription does not require it.", "External · optional"],
    ],
    flow: [
      ["01", "Record", "Choose screen, microphone, and system-audio sources from the recorder workspace."],
      ["02", "Transcribe", "Receive live and final transcript events while local models handle speech."],
      ["03", "Review", "Clean diarization, inspect speaker-labelled text, and play the source recording."],
      ["04", "Return", "Open previous sessions from the meetings list without reprocessing the media."],
    ],
    slides: [
      {
        src: "meeting/meeting-detail.webp",
        alt: "Meeting Whisperer detail page with a real video recording, playback timeline, speaker-labelled transcript, and diarization controls",
        label: "Meeting detail",
        title: "Recording and diarized transcript",
        description: "Review the source video beside its timeline, clean transcript, and speaker labels.",
      },
      {
        src: "meeting/recorder.webp",
        alt: "Meeting Whisperer recorder with screen, microphone, system-audio, and transcript controls",
        label: "Capture workspace",
        title: "Choose what the meeting can hear",
        description: "Control screen, microphone, system audio, and live transcription from one workspace.",
      },
      {
        src: "meeting/meetings-list.webp",
        alt: "Meeting Whisperer meeting history showing saved recordings, dates, durations, and processing status",
        label: "Meeting history",
        title: "Return without reprocessing",
        description: "Open saved sessions with their duration, status, recording, and transcript already connected.",
      },
    ],
  },
  ielts: {
    eyebrow: "AI-assisted language learning",
    title: "IELTS Mock Examiner",
    subtitle: "A full-stack practice platform combining speaking sessions, structured writing feedback, progress tracking, and configurable question banks.",
    accent: "teal",
    repository: "https://github.com/TJ-Rustamov/ielts_mock_examiner",
    stack: ["React", "Vite", "Django", "Channels", "Gemini", "faster-whisper", "Kokoro TTS", "SQLite", "Docker"],
    metrics: [["Real screens", "Learner and admin workflows"], ["Local speech AI", "STT and TTS are self-hosted"], ["One external model", "Gemini handles evaluation"]],
    architecture: [
      ["Experience", "React and Vite deliver learner dashboards, speaking, writing, and admin interfaces.", "Self-hosted"],
      ["Application", "Django, REST APIs, and Channels coordinate authentication and realtime sessions.", "Self-hosted"],
      ["Listen", "faster-whisper converts candidate speech to text without a hosted STT service.", "Local model"],
      ["Speak", "Kokoro generates examiner prompts without a hosted TTS service.", "Local model"],
      ["Evaluate", "Gemini is the only external AI layer and produces structured scoring and feedback.", "External LLM"],
      ["Persist", "SQLite and an in-memory channel layer support the current single-instance setup.", "Local"],
    ],
    flow: [
      ["01", "Choose", "Learners enter speaking or writing practice from a shared dashboard."],
      ["02", "Practice", "Question progression, timers, and speech prompts mirror a structured test journey."],
      ["03", "Evaluate", "The completed response is transcribed locally before Gemini receives text for assessment."],
      ["04", "Improve", "Criterion-level reports and saved attempts make the next practice session more focused."],
    ],
    slides: [
      { src: "ielts/dashboard.webp", alt: "IELTS Mock Examiner learner dashboard with progress and recent sessions", label: "Overview", title: "Learner dashboard", description: "Choose a module, review recent sessions, and see progress over time." },
      { src: "ielts/speaking-process.webp", alt: "IELTS speaking test interface captured from the application", label: "Speaking", title: "Structured speaking session", description: "Move through examiner prompts and timed responses in a guided test flow." },
      { src: "ielts/speaking-evaluation.webp", alt: "IELTS speaking evaluation report with scores and feedback", label: "Speaking feedback", title: "Criterion-level speaking report", description: "Review scores, transcript evidence, and practical suggestions after the session." },
      { src: "ielts/writing-process.webp", alt: "IELTS writing task interface captured from the application", label: "Writing", title: "Focused writing workspace", description: "Work against the active prompt in a clean, timed practice environment." },
      { src: "ielts/writing-evaluation.webp", alt: "IELTS writing evaluation report with criterion scores", label: "Writing feedback", title: "Writing evaluation and rewrite", description: "Compare criterion scores, detailed feedback, and an enhanced response." },
      { src: "ielts/admin.webp", alt: "IELTS Mock Examiner administration interface and question bank", label: "Administration", title: "Configurable question bank", description: "Manage prompts, models, voices, and assessment content behind the learner experience." },
    ],
  },
  graduation: {
    eyebrow: "Central Asian University · Class of 2026",
    title: "A once-in-a-lifetime chapter, carried forward.",
    subtitle: "Four years gave me more than a Computer Science degree. They gave me people to learn beside, problems worth staying with, and the confidence to build beyond the classroom.",
    accent: "gold",
    university: "https://centralasian.uz/",
    program: "https://centralasian.uz/computer-science",
    heroImage: {
      src: "graduation/memories/ceremony-finale-2000.webp",
      srcSet: "graduation/memories/ceremony-finale-1000.webp 1000w, graduation/memories/ceremony-finale-2000.webp 2000w",
      alt: "Central Asian University graduates celebrating together on the 2026 graduation stage",
    },
    reflectionPhotos: [
      {
        src: "graduation/memories/reflection-classroom.webp",
        alt: "Computer Science classmates sharing an informal moment together in a university lecture room",
        position: "center 55%",
      },
      {
        src: "graduation/memories/reflection-campus.webp",
        alt: "University friends sitting together on wooden steps during an ordinary day on campus",
        position: "center 58%",
      },
    ],
    beforeGraduation: [
      {
        src: "graduation/memories/before-cau-1280.webp",
        srcSet: "graduation/memories/before-cau-800.webp 800w, graduation/memories/before-cau-1280.webp 1280w",
        alt: "A casual group photograph of classmates together at Central Asian University",
        label: "At CAU",
        title: "Classmates became teammates",
        description: "The ordinary days—shared rooms, difficult questions, and work in progress—became the memories that stayed.",
      },
      {
        src: "graduation/memories/before-tech-event.webp",
        alt: "A small group of students together at a Central Asian University technology event",
        label: "Beyond class",
        title: "Curiosity travelled beyond the classroom",
        description: "Events and new environments gave us another place to test ideas, meet people, and see where our skills could lead.",
        position: "center 38%",
      },
      {
        src: "graduation/memories/before-team-2000.webp",
        srcSet: "graduation/memories/before-team-1000.webp 1000w, graduation/memories/before-team-2000.webp 2000w",
        alt: "A group of classmates standing together outdoors during their university years",
        label: "Along the way",
        title: "Progress was something we made together",
        description: "University was shaped as much by the people beside me as by the subjects in front of me.",
      },
      {
        src: "graduation/memories/before-studio-group.webp",
        alt: "A large group of classmates laughing together during a university photo session",
        label: "Together",
        title: "The serious work still left room for joy",
        description: "The strongest teams were not only productive. They made difficult years lighter and milestones more meaningful.",
      },
    ],
    ceremony: [
      {
        src: "graduation/memories/ceremony-diploma-2000.webp",
        srcSet: "graduation/memories/ceremony-diploma-1000.webp 1000w, graduation/memories/ceremony-diploma-2000.webp 2000w",
        alt: "A Central Asian University Computer Science graduate receiving a diploma on stage",
        label: "The diploma moment",
        title: "Years of work made visible",
        description: "One brief moment on stage held the weight of every project, setback, deadline, and small win that came before it.",
      },
      {
        src: "graduation/memories/ceremony-classmates.webp",
        alt: "Computer Science classmates gathered together in Central Asian University graduation gowns",
        label: "Computer Science classmates",
        title: "The people behind the degree",
        description: "A final formal photograph captured the group that shared the questions, pressure, progress, and celebration.",
      },
      {
        src: "graduation/memories/ceremony-cap-toss.webp",
        alt: "Central Asian University graduates throwing their caps together outside the campus",
        label: "The cap toss",
        title: "A celebration bigger than one person",
        description: "The moment felt most complete when it was shared with the whole graduating class.",
      },
      {
        src: "graduation/memories/ceremony-finale-2000.webp",
        srcSet: "graduation/memories/ceremony-finale-1000.webp 1000w, graduation/memories/ceremony-finale-2000.webp 2000w",
        alt: "The Central Asian University Class of 2026 celebrating together during the graduation ceremony",
        label: "Class of 2026",
        title: "A shared ending and many new beginnings",
        description: "The ceremony belonged to everyone on the stage—and to all the different directions we would take after it.",
      },
    ],
    poster: {
      src: "graduation/academic-poster.webp",
      alt: "Full Central Asian University capstone poster for IELTS Mock Examiner by A. Khasakhojaev and J. Rustamov, supervised by Eugene Castro",
      label: "Original academic capstone poster",
    },
  },
};
