export const caseStudies = {
  meeting: {
    eyebrow: "Local-first voice intelligence",
    title: "Meeting Whisperer",
    subtitle: "A private meeting recorder that captures microphone and system audio, produces speaker-aware transcripts, and keeps every recording searchable.",
    accent: "pink",
    repository: "https://github.com/TJ-Rustamov/Meeting-whisperer",
    stack: ["React", "FastAPI", "WebSockets", "faster-whisper", "Silero VAD", "pyannote", "SQLite", "Docker"],
    metrics: [["Real captures", "Recorder, history, and transcript"], ["Local speech AI", "STT and diarization stay self-hosted"], ["Optional cloud", "LLM only for post-processing"]],
    architecture: [
      ["Capture", "React, MediaRecorder, and AudioWorklet collect microphone and desktop audio.", "Local"],
      ["Stream", "FastAPI and WebSockets move live audio and transcript events through the application.", "Self-hosted"],
      ["Transcribe", "Silero VAD, faster-whisper, and optional pyannote process speech and speakers.", "Local model"],
      ["Store", "SQLite plus local audio and video files preserve meetings and transcript history.", "Local"],
      ["Enrich", "An external LLM can be enabled for summaries or cleanup; core transcription does not require it.", "External · optional"],
    ],
    flow: [
      ["01", "Record", "Choose screen, microphone, and system-audio sources from the recorder workspace."],
      ["02", "Transcribe", "Receive live and final transcript events while local models handle speech."],
      ["03", "Review", "Clean diarization, inspect speaker-labelled text, and play the source recording."],
      ["04", "Return", "Open previous sessions from the meetings list without reprocessing the media."],
    ],
    gallery: [
      { src: "meeting/meeting-detail.webp", alt: "Meeting Whisperer detail page with a real video recording, playback timeline, speaker-labelled transcript, and diarization controls", label: "Meeting detail and diarized transcript", featured: true },
      { src: "meeting/recorder.webp", alt: "Meeting Whisperer recorder with screen, microphone, system-audio, and transcript controls", label: "Recorder workspace" },
      { src: "meeting/meetings-list.webp", alt: "Meeting Whisperer meeting history showing saved recordings, dates, durations, and processing status", label: "Searchable meeting history" },
    ],
  },
  ielts: {
    eyebrow: "AI-assisted language learning",
    title: "IELTS Mock Examiner",
    subtitle: "A full-stack practice platform combining speaking sessions, structured writing feedback, progress tracking, and configurable question banks.",
    accent: "teal",
    repository: "https://github.com/TJ-Rustamov/ielts_mock_examiner",
    stack: ["React", "Vite", "Django", "Channels", "Gemini", "faster-whisper", "Kokoro TTS", "SQLite", "Docker"],
    metrics: [["Real screens", "Learner and admin workflows"], ["Local speech AI", "STT and TTS are self-hosted"], ["One external model", "Gemini handles evaluation"]],
    architecture: [
      ["Experience", "React and Vite deliver learner dashboards, speaking, writing, and admin interfaces.", "Self-hosted"],
      ["Application", "Django, REST APIs, and Channels coordinate authentication and realtime sessions.", "Self-hosted"],
      ["Listen", "faster-whisper converts candidate speech to text without a hosted STT service.", "Local model"],
      ["Speak", "Kokoro generates examiner prompts without a hosted TTS service.", "Local model"],
      ["Evaluate", "Gemini is the only external AI layer and produces structured scoring and feedback.", "External LLM"],
      ["Persist", "SQLite and an in-memory channel layer support the current single-instance setup.", "Local"],
    ],
    flow: [
      ["01", "Choose", "Learners enter speaking or writing practice from a shared dashboard."],
      ["02", "Practice", "Question progression, timers, and speech prompts mirror a structured test journey."],
      ["03", "Evaluate", "The completed response is transcribed locally before Gemini receives text for assessment."],
      ["04", "Improve", "Criterion-level reports and saved attempts make the next practice session more focused."],
    ],
    gallery: [
      { src: "ielts/dashboard.webp", alt: "IELTS Mock Examiner learner dashboard with progress and recent sessions", label: "Learner dashboard", featured: true },
      { src: "ielts/speaking-process.webp", alt: "IELTS speaking test interface captured from the application", label: "Speaking session" },
      { src: "ielts/speaking-evaluation.webp", alt: "IELTS speaking evaluation report with scores and feedback", label: "Speaking feedback" },
      { src: "ielts/writing-process.webp", alt: "IELTS writing task interface captured from the application", label: "Writing task" },
      { src: "ielts/writing-evaluation.webp", alt: "IELTS writing evaluation report with criterion scores", label: "Writing feedback" },
      { src: "ielts/admin.webp", alt: "IELTS Mock Examiner administration interface and question bank", label: "Admin controls" },
    ],
  },
  graduation: {
    eyebrow: "BSc Computer Science · Class of 2026",
    title: "Central Asian University Graduation",
    subtitle: "The education, people, and applied work that shaped my move from computer science student to full-stack AI engineer.",
    accent: "orange",
    repository: "https://github.com/TJ-Rustamov/ielts_mock_examiner",
    university: "https://centralasian.uz/",
    program: "https://centralasian.uz/computer-science",
    stack: ["Computer Science", "Software Engineering", "Applied AI", "System Design", "Teamwork", "Technical Communication"],
    metrics: [["BSc Computer Science", "Central Asian University"], ["Engineering School", "Tashkent, Uzbekistan"], ["Class of 2026", "From study to production AI"]],
    gallery: [
      { src: "graduation/academic-poster.webp", alt: "Full Central Asian University capstone poster for IELTS Mock Examiner by A. Khasakhojaev and J. Rustamov, supervised by Eugene Castro", label: "Original academic capstone poster", featured: true },
    ],
  },
};
